server:
  port: 9009

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: EMPLOYEE-SERVICE
            uri: http://localhost:9002
            predicates:
             - Path=/employees/**
          - id: CUSTOMER-SERVICE
            uri: http://localhost:9004
            predicates:
              - Path=/customers/**
          - id: PRODUCT-SERVICE
            uri: http://localhost:9003
            predicates:
              - Path=/products/**
          - id: ORDER-SERVICE
            uri: http://localhost:9006
            predicates:
              - Path=/orders/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
